name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Reformat repository for PythonAPI
      run: |
        git checkout --orphan python-api || git checkout python-api 
        mv PythonAPI/ ../
        rm -r *
        mv ../PythonAPI/* ./
        git add . -f
        git commit -m "Pushing PythonAPI/ to python-api branch"
        git push origin python-api 
